# Generated by Django 2.2.1 on 2019-05-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
